FROM apache/spark:3.5.1

USER root

WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
        gcc \
        g++ \
        python3-dev \
        librdkafka-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-spark.txt .

RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir -r requirements-spark.txt

COPY . .

ENV PYTHONPATH=/app