NON_DIAGNOSTIC_TERMS = [
    "Healthy",
    "Healthy Volunteers",
    "Healthy Volunteer",
    "Healthy Subjects",
    "Healthy Participants",
    "Healthy Aging",
    "Aging",
    "Pregnancy",
    "Pharmacokinetics",
    "Bioequivalence",
    "Anesthesia",
    "General Anesthesia",
    "Nerve Block",
    "Contraception",
]